INSERT INTO PRODUTO (ID, DESCRICAO, VALOR) VALUES (DEFAULT, 'Arroz', 20);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR) VALUES (DEFAULT, 'Feijão', 10);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR) VALUES (DEFAULT, 'Macarrão', 15);

INSERT INTO VENDA (ID, DATA) VALUES (1, '2023-10-10');
INSERT INTO VENDA (ID, DATA) VALUES (2, '2023-11-11');

INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (3, 1, 1);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (2, 2, 1);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (5, 1, 2);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (4, 3, 2);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (2, 2, 1);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (1, 1, 2);
INSERT INTO ITEM_VENDA (QTD, PRODUTO_ID, VENDA_ID) VALUES (3, 3, 1);

